import { Label as LabelPF, LabelProps as LabelPropsPF } from '@patternfly/react-core';

import { EmptyStateSymbol } from 'components/EmptyStateSymbol/EmptyStateSymbol';

import { uiLogger } from 'services/uiLogger';

interface ILabelMapperItem {
  text: string;
  color: LabelPropsPF['color'];
}

export type ILabelMapper<Types> = {
  [key in Types as string]: ILabelMapperItem;
};

interface ILabelMapperProps {
  mapperItem?: ILabelMapperItem;
  onRemove?: () => void;
}

/**
 * Represents a Label generated by label mapper item.
 *
 * @param mapperItem - the mapper item that will be used to generate the label
 * @param onRemove - if passed, displays remove icon inside label
 */
export const LabelMapper = ({ mapperItem, onRemove }: ILabelMapperProps) => {
  if (!mapperItem) {
    uiLogger.error(`Error attempting to get mapper item: mapper item undefined`);
  }
  return mapperItem ? (
    <LabelPF color={mapperItem.color} onClose={onRemove}>
      {mapperItem.text}
    </LabelPF>
  ) : (
    <EmptyStateSymbol text={false} />
  );
};
