import { Label as LabelPF, LabelProps as LabelPropsPF } from '@patternfly/react-core';

import { EmptyStateSymbol } from 'components/EmptyStateSymbol/EmptyStateSymbol';

import { uiLogger } from 'services/uiLogger';

interface ILabelMapperItem {
  text: string;
  color: LabelPropsPF['color'];
}

export type ILabelMapper<Type> = {
  [key in Type as string | number | symbol]: ILabelMapperItem;
};

interface ILabelProps {
  mapper: ILabelMapperItem | undefined;
}

/**
 * Represents a Label generated by labelMapper object.
 *
 * @param mapper - the mapper object that will be used to generate the label
 */
export const LabelMapper = ({ mapper }: ILabelProps) => {
  if (!mapper) {
    uiLogger.error(`Error attempting get mapper: mapper undefined`);
  }
  return mapper ? <LabelPF color={mapper.color}>{mapper.text}</LabelPF> : <EmptyStateSymbol />;
};
