export const PageTitles = {
  projects: 'Projects',
  projectDetail: 'Project Detail',
  projectCreate: 'Create Project',
  projectEdit: 'Update Project',
  products: 'Products',
  buildConfig: 'Build Configs',
  groupConfig: 'Group Configs',
  builds: 'Builds',
  groupBuilds: 'Group Builds',
  artifacts: 'Artifacts',
  repositories: 'SCM Repositories',
  administration: 'Administration',
  pageNotFound: 'Page not found',
};
